// Report templates for the book-level "PDF report" download.
//
// DESIGN: every template shares PRINT_STYLE (printStyle.ts), built from tokens.ts —
// ink text, hairline rules, colour only for meaning, two weights, sentence case.
//
// MONEY: every {{...}} amount placeholder is filled with formatCurrency(paisa),
// which already emits the "Rs." prefix. Templates must therefore NOT add their own
// literal "Rs " prefix, or output reads "Rs Rs. 1,234.56".
//
// Summary lines keep the exact "Label: <strong>value</strong>" shape so every
// figure can be reconciled against the book it came from.
import { PRINT_STYLE } from './printStyle';

const doc = (title: string, sub: string, table: string, summary: string) => `
<html>
<head>
  <meta charset="utf-8" />
  <style>${PRINT_STYLE}</style>
</head>
<body>
  <div class="doc-head">
    <div>
      <p class="doc-business">{{business_name}}</p>
      <p class="doc-sub">${sub}</p>
    </div>
    <div>
      <p class="doc-title">${title}</p>
    </div>
  </div>
  <table>
    ${table}
    {{rows}}
  </table>
  <div class="summary">
    ${summary}
  </div>
  <p class="doc-foot">Generated by AL-REEF</p>
</body>
</html>
`;

export const CASH_RECEIPT_TEMPLATE = doc(
  'Cash book statement',
  'Period: {{period}}',
  '<tr><th>Date</th><th>Type</th><th>Description</th><th>Category</th><th class="num">Amount</th></tr>',
  `<p class="fig-in">Total in: <strong>{{totalIn}}</strong></p>
    <p class="fig-out">Total out: <strong>{{totalOut}}</strong></p>
    <p class="grand">Net balance: <strong>{{netBalance}}</strong></p>`
);

export const EXPENSE_REPORT_TEMPLATE = doc(
  'Expense report',
  'Period: {{period}}',
  '<tr><th>Date</th><th>Description</th><th>Category</th><th class="num">Amount</th></tr>',
  `<p class="grand fig-out">Total expenses: <strong>{{total}}</strong></p>`
);

export const STOCK_REPORT_TEMPLATE = doc(
  'Stock report',
  'Period: {{period}}',
  '<tr><th>Item</th><th>Location</th><th class="num">Stock in</th><th class="num">Stock out</th><th class="num">Net qty</th><th class="num">In value</th><th class="num">Out value</th></tr>',
  `<p>Total purchase value (in): <strong>{{totalInValue}}</strong></p>
    <p>Total sale value (out): <strong>{{totalOutValue}}</strong></p>`
);

// Stock in / Stock out: one movement per row — the same rows the report screens list.
// {{direction}} is "in" or "out" so the document is unmistakably one or the other.
export const STOCK_MOVEMENT_TEMPLATE = doc(
  'Stock {{direction}} report',
  'Period: {{period}}',
  '<tr><th>Item</th><th>Date</th><th class="num">Qty {{direction}}</th><th class="num">Rate</th><th class="num">Amount</th></tr>',
  `<p>Entries: <strong>{{entries}}</strong></p>
    <p>Total qty {{direction}}: <strong>{{totalQty}}</strong></p>
    <p class="grand">Total amount ({{amountLabel}}): <strong>{{totalAmount}}</strong></p>`
);

export const BILL_REPORT_TEMPLATE = doc(
  'Bill book report',
  'Period: {{period}}',
  '<tr><th>Bill #</th><th>Date</th><th>Customer</th><th class="num">Total</th><th class="num">Paid</th><th class="num">Due</th></tr>',
  `<p>Total bills: <strong>{{billCount}}</strong></p>
    <p>Total billed: <strong>{{totalBilled}}</strong></p>
    <p class="fig-in">Total received: <strong>{{totalPaid}}</strong></p>
    <p class="grand fig-out">Total outstanding: <strong>{{totalDue}}</strong></p>`
);

// Staff is a roster, not period data — it shows an "As of" date, not a period.
export const STAFF_REPORT_TEMPLATE = doc(
  'Staff report',
  'As of {{asOfDate}}',
  '<tr><th>Name</th><th>Role</th><th>Phone</th><th>Area</th><th>Joined</th><th>Status</th><th class="num">Monthly salary</th></tr>',
  `<p>Total staff: <strong>{{totalStaff}}</strong></p>
    <p>Active: <strong>{{activeStaff}}</strong></p>
    <p class="grand">Total monthly salary: <strong>{{totalMonthlySalary}}</strong></p>`
);
