import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Transaction, CashEntry } from '../types';
import { formatCurrency, formatDate } from './calculations';
import { PRINT_STYLE, esc, printWord } from '../components/Download/printStyle';

/** One document shell for these exports — the same print design as the book reports. */
const shell = (business: string, title: string, sub: string, body: string) => `<!DOCTYPE html>
<html><head><meta charset="utf-8" /><style>${PRINT_STYLE}</style></head><body>
  <div class="doc-head">
    <div>
      <p class="doc-business">${esc(business)}</p>
      <p class="doc-sub">${sub}</p>
    </div>
    <div><p class="doc-title">${esc(title)}</p></div>
  </div>
  ${body}
  <p class="doc-foot">Generated by AL-REEF</p>
</body></html>`;

/** Whole-set totals, ideally the SQL summary the screen already shows. */
export type KhataTotals = { totalLena: number; totalDena: number; netBalance: number };

/**
 * Khata export (the ledger, or one customer's ledger). Pass `totals` from the same
 * SQL query the screen shows so paper and screen agree; without it they are derived
 * from `transactions`, which must then be the WHOLE filtered set, never one page.
 */
export const generateTransactionPDF = async (
  transactions: Transaction[],
  businessName: string,
  userName: string,
  reportTitle: string = 'Khata report',
  totals?: KhataTotals
): Promise<void> => {
  const sum = (type: 'lena' | 'dena') => transactions.filter(t => t.type === type).reduce((s, t) => s + t.amount_paisa, 0);
  const totalLena = totals?.totalLena ?? sum('lena');
  const totalDena = totals?.totalDena ?? sum('dena');
  const netBalance = totals?.netBalance ?? totalLena - totalDena;
  const hasRunning = transactions.some(t => typeof (t as any).runningBalance === 'number');

  const rows = transactions.length === 0
    ? `<tr><td class="empty" colspan="${hasRunning ? 6 : 5}">No transactions</td></tr>`
    : transactions.map(t => {
        // Lena = credit given (money out, red); dena = payment taken (money in, green).
        const cls = t.type === 'lena' ? 'out' : 'in';
        return `<tr>
          <td>${esc(formatDate(t.date))}</td>
          <td>${esc(t.partyName)}</td>
          <td class="${cls}">${esc(printWord(t.type))}</td>
          <td class="num ${cls}">${formatCurrency(t.amount_paisa)}</td>
          ${hasRunning ? `<td class="num">${formatCurrency(Math.abs((t as any).runningBalance ?? 0))}</td>` : ''}
          <td>${esc(t.notes || '—')}</td>
        </tr>`;
      }).join('');

  const html = shell(
    businessName,
    reportTitle,
    `Prepared by ${esc(userName)} · ${esc(new Date().toLocaleDateString('en-PK'))}`,
    `<table>
      <tr><th>Date</th><th>Party</th><th>Type</th><th class="num">Amount</th>${hasRunning ? '<th class="num">Balance</th>' : ''}<th>Notes</th></tr>
      ${rows}
    </table>
    <div class="summary">
      <p>Entries: <strong>${transactions.length}</strong></p>
      <p class="fig-out">Total lena: <strong>${formatCurrency(totalLena)}</strong></p>
      <p class="fig-in">Total dena: <strong>${formatCurrency(totalDena)}</strong></p>
      <p class="grand">Net balance: <strong>${netBalance < 0 ? '−' : ''}${formatCurrency(Math.abs(netBalance))}</strong></p>
    </div>`
  );

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Khata report' });
};

/** Legacy cash export — only the retired staff/CashBookScreen still imports it. */
export const generateCashbookPDF = async (
  cashBook: CashEntry[],
  businessName: string,
  userName: string
): Promise<void> => {
  const totalIn = cashBook.filter(e => e.direction === 'in').reduce((s, e) => s + e.amount_paisa, 0);
  const totalOut = cashBook.filter(e => e.direction === 'out').reduce((s, e) => s + e.amount_paisa, 0);
  const balance = totalIn - totalOut;

  const rows = cashBook.map(e => {
    const cls = e.direction === 'in' ? 'in' : 'out';
    return `<tr><td>${esc(formatDate(e.date))}</td><td>${esc(e.description)}</td>` +
           `<td class="${cls}">${esc(printWord(e.direction))}</td><td class="num ${cls}">${formatCurrency(e.amount_paisa)}</td></tr>`;
  }).join('') || '<tr><td class="empty" colspan="4">No entries</td></tr>';

  const html = shell(
    businessName,
    'Cash book report',
    `Prepared by ${esc(userName)} · ${esc(new Date().toLocaleDateString('en-PK'))}`,
    `<table><tr><th>Date</th><th>Description</th><th>Direction</th><th class="num">Amount</th></tr>${rows}</table>
    <div class="summary">
      <p>Entries: <strong>${cashBook.length}</strong></p>
      <p class="fig-in">Total in: <strong>${formatCurrency(totalIn)}</strong></p>
      <p class="fig-out">Total out: <strong>${formatCurrency(totalOut)}</strong></p>
      <p class="grand">Balance: <strong>${balance < 0 ? '−' : ''}${formatCurrency(Math.abs(balance))}</strong></p>
    </div>`
  );

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share cash report' });
};

/** A plain table of rows (report screens' export). Keys become sentence-case headers. */
export const generateGenericPDF = async (
  title: string,
  data: Record<string, any>[],
  businessName: string = 'AL-REEF'
): Promise<void> => {
  if (data.length === 0) return;
  const headers = Object.keys(data[0]);
  const head = headers.map(h => `<th>${esc(printWord(h.replace(/_/g, ' ')))}</th>`).join('');
  const rows = data.map(row => `<tr>${headers.map(h => `<td>${esc(row[h])}</td>`).join('')}</tr>`).join('');

  const html = shell(
    businessName,
    title,
    `Generated ${esc(new Date().toLocaleDateString('en-PK'))}`,
    `<table><tr>${head}</tr>${rows}</table>`
  );

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `Share ${title}` });
};
